name: 🐞 Rapport de bug
description: Signalez un problème pour permettre d'améliorer le projet
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Merci de signaler ce problème ! 👋
        
        Remplissez ce formulaire avec le **maximum de détails** pour nous aider à reproduire et résoudre le bug rapidement.
    
        💡 **Astuce** : Vous pouvez coller des images directement dans les zones de texte !\n\n
  
  - type: textarea
    id: description
    attributes:
      label: 📝 Description du problème
      description: Décrivez clairement et précisément le problème rencontré (page, fonctionnalité, etc.)
      placeholder: Ex. L'application plante quand je clique sur le bouton "Sauvegarder"
    validations:
      required: true

    - type: markdown
      attributes:
        value: ""
  
    - type: textarea
      id: expected
      attributes:
        label: Que devrait-il se passer normalement ?
        description: Décrivez clairement et précisément ce que vous attendiez.
        placeholder: Ex. La page devrait se charger sans erreur et afficher...
      validations:
        required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔄 Étapes pour reproduire
      description: Listez les étapes exactes pour reproduire le problème
      placeholder: |
        1. Aller à la page '...'
        2. Cliquer sur '...'
        3. Saisir '...'
        4. Observer l'erreur
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## 🔧 Informations techniques
        
        *Ces informations nous aident à reproduire le problème dans le bon environnement*\n
        
  - type: dropdown
    id: os
    attributes:
      label: Système d'exploitation
      description: Quel système utilisez-vous ?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (autre)
        - iOS
        - Android
        - Autre
    validations:
      required: true

  - type: markdown
    attributes:
      value: ""

  - type: dropdown
    id: browser
    attributes:
      label: Navigateur
      description: Quel navigateur utilisez-vous ? (si applicable)
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Brave
        - Application mobile
        - Autre

  - type: markdown
    attributes:
      value: ""

  - type: input
    id: browser-version
    attributes:
      label: Version du navigateur (si vous la connaissez)
      description: Menu → À propos de [Navigateur] pour connaître la version
      placeholder: Ex. Chrome 120.0.6099.109

  - type: markdown
    attributes:
      value: |
        ---
        ## 🚨 Messages d'erreur et captures d'écran

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Captures d'écran
      description: Glissez-déposez vos images ou collez-les directement (Ctrl+V)
      placeholder: Ajoutez des captures d'écran si nécessaire
    
  - type: markdown
    attributes:
      value: ""

  - type: textarea
    id: error-logs
    attributes:
      label: Messages d'erreur et logs
      description: |
        • Copiez-collez les messages d'erreur exacts (si visibles)
        • Ouvrez la console (F12 → Console) et copiez/collez les erreurs en rouge
      placeholder: |
        Messages d'erreur visibles :
        [collez ici]

        Erreurs de la console :
        [collez ici]
      render: text

  - type: markdown
    attributes:
      value: ""

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Vérifications finales
      options:
        - label: J'ai fourni suffisamment d'informations pour reproduire le problème
          required: true 