name: "\U0001F41E Rapport de bug"
description: Signalez un problème pour permettre d'améliorer le projet
title: '[BUG] '
labels:
  - bug
  - needs-triage
body:
  - type: markdown
    attributes:
      value: "## Merci de signaler ce problème ! \U0001F44B\n\nRemplissez ce formulaire avec le **maximum de détails** pour nous aider à reproduire et résoudre le bug rapidement.\n\n\U0001F4A1 **Astuce** : Vous pouvez coller des images directement dans les zones de texte !\\n\\n\n"
  - type: textarea
    id: description
    attributes:
      label: "\U0001F4DD Description du problème"
      description: >-
        Décrivez clairement et précisément le problème rencontré (page,
        fonctionnalité, etc.)
      placeholder: Ex. L'application plante quand je clique sur le bouton "Sauvegarder"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |+

  - type: textarea
    id: steps
    attributes:
      label: "\U0001F504 Étapes pour reproduire"
      description: Listez les étapes exactes pour reproduire le problème
      placeholder: |
        1. Aller à la page '...'
        2. Cliquer sur '...'
        3. Saisir '...'
        4. Observer l'erreur
    validations:
      required: true
  - type: markdown
    attributes:
      value: |+

  - type: textarea
    id: expected
    attributes:
      label: ✅ Résultat attendu
      description: Que devrait-il se passer normalement ?
      placeholder: Ex. La page devrait se charger sans erreur et afficher...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |+


  - type: markdown
    attributes:
      value: "---\n## \U0001F527 Informations techniques\n\n*Ces informations nous aident à reproduire le problème dans le bon environnement*\\n\n"
  - type: dropdown
    id: os
    attributes:
      label: Système d'exploitation
      description: Quel système utilisez-vous ?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (autre)
        - iOS
        - Android
        - Autre
    validations:
      required: true
  - type: markdown
    attributes:
      value: |+

  - type: dropdown
    id: browser
    attributes:
      label: Navigateur
      description: Quel navigateur utilisez-vous ? (si applicable)
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Brave
        - Application mobile
        - Autre
  - type: markdown
    attributes:
      value: |+

  - type: input
    id: browser-version
    attributes:
      label: Version du navigateur
      description: 'Menu → À propos de [Navigateur] pour connaître la version'
      placeholder: Ex. Chrome 120.0.6099.109
  - type: markdown
    attributes:
      value: "---\n## \U0001F6A8 Messages d'erreur et captures d'écran\n"
  - type: textarea
    id: error-messages
    attributes:
      label: Messages d'erreur
      description: Copiez-collez les messages d'erreur exacts (si visibles)
      placeholder: Pas de message d'erreur visible
      render: text
  - type: markdown
    attributes:
      value: |+

  - type: textarea
    id: console-logs
    attributes:
      label: Console du navigateur
      description: Ouvrez la console (F12 → Console) et copiez/collez les erreurs en rouge
      placeholder: Pas d'erreur dans la console
      render: text
  - type: markdown
    attributes:
      value: |+

  - type: textarea
    id: screenshots
    attributes:
      label: "\U0001F4F8 Captures d'écran"
      description: Glissez-déposez vos images ou collez-les directement (Ctrl+V)
      placeholder: Ajoutez des captures d'écran si nécessaire
  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Vérifications finales
      options:
        - label: J'ai fourni suffisamment d'informations pour reproduire le problème
          required: true
